server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app
    username: root
    password: amit1234
    driver-class-name: com.mysql.jdbc.cj.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  image: images/